apiVersion: v1
kind: Service
metadata:
  name: apple-clusterip
spec:
  selector:
    app: apple-app
  ports:
    - port: 9000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-deployment
spec:
  selector:
    matchLabels:
      app: apple-app
  template:
    metadata:
      labels:
        app: apple-app
    spec:
      containers:
        - name: apple-app
          image: ajduet/apple
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
