apiVersion: v1
kind: Service
metadata:
  name: banana-clusterip
spec:
  selector:
    app: banana-app
  ports:
    - port: 9000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-deployment
spec:
  selector:
    matchLabels:
      app: banana-app
  template:
    metadata:
      labels:
        app: banana-app
    spec:
      containers:
        - name: banana-app
          image: ajduet/banana
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
