apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
spec:
  type: NodePort
  selector:
    app: gateway-app
  ports:
    - port: 9002
      targetPort: 8080
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-app
          image: ajduet/fruit-gateway
          resources:
            limits:
              memory: "1G"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_URLS_BANANA
              valueFrom:
                configMapKeyRef:
                  key: banana.service.name
                  name: fruit-configmap
            - name: SERVICE_URLS_APPLE
              valueFrom:
                configMapKeyRef:
                  key: apple.service.name
                  name: fruit-configmap
